// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhr0TsoS-MBS4i66f3hNWjVWSh-2355Wo',
    appId: '1:50078598937:web:95f3cc7afd7a42d4c3a788',
    messagingSenderId: '50078598937',
    projectId: 'evocapp-4d466',
    authDomain: 'evocapp-4d466.firebaseapp.com',
    storageBucket: 'evocapp-4d466.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNDBle2yJiDaYGId1gZ2Bv6qdj3OkMdE',
    appId: '1:50078598937:android:8df74629d9a1b6b8c3a788',
    messagingSenderId: '50078598937',
    projectId: 'evocapp-4d466',
    storageBucket: 'evocapp-4d466.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTiIAqTRMyZZUB5nEoTl9YIvf_5NpFDEU',
    appId: '1:50078598937:ios:3c8447eb16a3b96fc3a788',
    messagingSenderId: '50078598937',
    projectId: 'evocapp-4d466',
    storageBucket: 'evocapp-4d466.firebasestorage.app',
    iosBundleId: 'com.example.evocapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTiIAqTRMyZZUB5nEoTl9YIvf_5NpFDEU',
    appId: '1:50078598937:ios:3c8447eb16a3b96fc3a788',
    messagingSenderId: '50078598937',
    projectId: 'evocapp-4d466',
    storageBucket: 'evocapp-4d466.firebasestorage.app',
    iosBundleId: 'com.example.evocapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhr0TsoS-MBS4i66f3hNWjVWSh-2355Wo',
    appId: '1:50078598937:web:3590d4cda703ccfec3a788',
    messagingSenderId: '50078598937',
    projectId: 'evocapp-4d466',
    authDomain: 'evocapp-4d466.firebaseapp.com',
    storageBucket: 'evocapp-4d466.firebasestorage.app',
  );

}